# Generated by Django 4.2 on 2023-04-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_textm',
            new_name='question_text',
        ),
    ]
